module.exports = {
  port: process.env.PORT || 3001,
  nodeEnv: process.env.NODE_ENV || 'development',
  databaseUrl: process.env.DATABASE_URL || 'postgresql://postgres:postgres@db:5432/financial_forge',
  jwtSecret: process.env.JWT_SECRET || 'dev-secret-change-in-production-min-32-chars-long',
  jwtExpiry: process.env.JWT_EXPIRY || '7d',
  frontendUrl: process.env.FRONTEND_URL || 'http://localhost:5173',
  finnhubApiKey: process.env.FINNHUB_API_KEY || '',
  geminiApiKey: process.env.GEMINI_API_KEY || '',
  anthropicApiKey: process.env.ANTHROPIC_API_KEY || '',
  llmProvider: process.env.LLM_PROVIDER || 'gemini',
  embeddingProvider: process.env.EMBEDDING_PROVIDER || 'google',
  ragChunkSize: parseInt(process.env.RAG_CHUNK_SIZE || '500', 10),
  ragChunkOverlap: parseInt(process.env.RAG_CHUNK_OVERLAP || '50', 10),
  ragTopK: parseInt(process.env.RAG_TOP_K || '5', 10),
};
